name: sonatype
on:
  push:
    branches: [master]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - uses: olafurpg/setup-gpg@v2
      - uses: peaceiris/actions-hugo@v2.2.2
        with: 
          hugo-version: '0.59.1'
          extended: true
      - name: Publish
        run: |
          git ls-remote --get-url origin
          sbt test ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - name: website
        run: |
          sbt clean docs/mdoc docs/unidoc
          cd website
          hugo
          cd public
          touch .nojekyll
      - name: gh-pages-deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY_PRIVATE }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: website/public
          